server:
  port: 8080

spring:
  application:
    name: sdm-backend-java

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  threads:
    virtual:
      enabled: true # Enable high-performance Virtual Threads (Project Loom)

#  config:
#    import: optional:file:.env

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Secure Dynamic Messaging (SDM) Configurations
sdm:
  # Used for derivation of per-tag keys
  derive-mode: legacy # "legacy" or "standard"
  master-key: "00000000000000000000000000000000"

  # Parameter names for encrypted mirroring
  enc-picc-data-param: picc_data
  enc-file-data-param: enc

  # Parameter names for plaintext mirroring
  uid-param: uid
  ctr-param: ctr

  # Parameter name for signature (always applied)
  sdmmac-param: cmac

  # Accept only SDM using LRP, disallow usage of AES
  require-lrp: false

app:
  security:
    aes-key: ${AES_KEY:MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=}
  ai-server:
    url: ${AI_SERVER_URL:http://localhost:5000}
  nfc-key: ${NFC_KEY:00112233445566778899AABBCCDDEEFF}

springdoc:
  swagger-ui:
    tags-sorter: alpha
  openapi:
    info:
      title: 오너 패스포트 API 문서
      description: NFC 정품 인증 및 NFT 소유권 연동 백엔드 API 명세서입니다.
      version: v0.0.1
